
baseURL = "https://yunmaoQu.github.io/"
languageCode = "cn-ZH"
title = "qingfeng's tech blog"
paginate = 11                       # 每页的文章数
enableEmoji = true                  # 支持 Emoji
enableRobotsTXT = true              # 支持 robots.txt
googleAnalytics = ""                # Google 统计 id
theme = "mogege" 

# Chroma 代码高亮 http://gohugo.io/content-management/syntax-highlighting/
pygmentsUseClasses = true # 使用自定义的代码高亮样式
[markup]
  [markup.highlight]
    codeFences = true
    anchorLineNos = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 4

[Permalinks]
 posts = "/:year/:month/:day/:filename"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
  since = "2024"                  # 站点建立时间。也是版权的开始年份
  author = "qingfeng"              # 作者名字
  avatar = ""                     # 头像
  subtitle = "The best time to plant a tree was 20 years ago. The second-best time is now."
  description = "qingfeng's tech blog"
  license = '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

  enableGitalk = false            # [主题依赖]gitalk 评论系统全局开关
  enableUtteranc = true           # [主题依赖]Utteranc 评论系统全局开关
  showPostSocialLinks = true      # [主题依赖]开启每一篇文章的 social-links 显示 (与主页显示与否无关)
  easySearchedEngine = "google"   # [主题依赖]Easy-Searched-Text 默认使用的搜索引擎
  toc = true                      # [主题依赖]是否开启目录
  autoCollapseToc = false         # [主题依赖]Auto expand and collapse toc
  mathjax = true                  # [主题依赖]是否使用mathjax（数学公式）

  [params.gitalk] # [主题依赖]Github: https://github.com/gitalk/gitalk
    clientId = "" # Your client ID
    clientSecret = "" # Your client secret
    repo = "" # The repo to store comments
    owner = "" # Your GitHub ID
    admin = "" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id = "location.pathname" # The unique id of the page.
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode = true # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "" # Set a proxy by 'cors-anywhere', 'cors-proxy' or the thoers.

  [params.utteranc] # [主题依赖]Homepage: https://utteranc.es
    repo = "" # The repo to store comments
    issueTerm = "" # the mapping between blog posts and GitHub issues. 
    theme = "" # Theme
    crossorigin = "" # default: anonymous

  [params.social] # [主题依赖]
    Github = "qingfeng503"
    Linked = ""
    Email = "mailto:ymqu823@gmail.com"
    